// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7Ut8GU0g5V87G-arbGM3T7U4suLIgds',
    appId: '1:184991413981:web:48af734293c4d47b7b8d34',
    messagingSenderId: '184991413981',
    projectId: 'syndra-4c237',
    authDomain: 'syndra-4c237.firebaseapp.com',
    storageBucket: 'syndra-4c237.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFoAPAUDcWwyp_PMQtgbJtlqce8fk1rSY',
    appId: '1:184991413981:android:9545a56bf42bdee67b8d34',
    messagingSenderId: '184991413981',
    projectId: 'syndra-4c237',
    storageBucket: 'syndra-4c237.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJalsyRXfmrYU4z17_DwNwqpeaKmVJs1Q',
    appId: '1:184991413981:ios:3ebf873cd9d193747b8d34',
    messagingSenderId: '184991413981',
    projectId: 'syndra-4c237',
    storageBucket: 'syndra-4c237.firebasestorage.app',
    iosBundleId: 'com.example.syndra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJalsyRXfmrYU4z17_DwNwqpeaKmVJs1Q',
    appId: '1:184991413981:ios:3ebf873cd9d193747b8d34',
    messagingSenderId: '184991413981',
    projectId: 'syndra-4c237',
    storageBucket: 'syndra-4c237.firebasestorage.app',
    iosBundleId: 'com.example.syndra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu7Ut8GU0g5V87G-arbGM3T7U4suLIgds',
    appId: '1:184991413981:web:4af0a5555dea30147b8d34',
    messagingSenderId: '184991413981',
    projectId: 'syndra-4c237',
    authDomain: 'syndra-4c237.firebaseapp.com',
    storageBucket: 'syndra-4c237.firebasestorage.app',
  );
}
